theme = "gruvbox_material_dark_soft"

[editor]
line-number = "relative"
true-color = true
cursorline = true
color-modes = true
auto-format = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
"i" = [ ":clipboard-yank", ":sh silicon --from-clipboard -l rs -f 'ComicCode Nerd Font=16' --theme 'gruvbox-dark' -b '#3c3836' --shadow-color '#282828' --shadow-blur-radius 30 --shadow-offset-x 0 --shadow-offset-y 0 --to-clipboard" ]
"H" = [ ":pipe prettier --parser html --stdin-filepath", "indent" ]
