theme = "gruvbox-fixed"

[editor]
line-number = "relative"
true-color = true
cursorline = true
color-modes = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
